<table width="100%" bgcolor="#808080" border="0" cellpadding="10">
    <tr>
        <td>
            <p class="foot" style="text-align:center; font-size:20px; font-weight:bold;">
                <a href="help.php">Help</a></p>
            <p class="foot" style="text-align:center; font-size:20px; font-weight:bold;">
                <a href="support.php">Support</a></p>
            <p class="foot" style="text-align:center; font-size:20px; font-weight:bold;">
                <a href="suggestion.php">Suggestions</a></p>
            <p class="foot" style="text-align:center; font-size:20px; font-weight:bold;">
                <a href="contact.php">Contact Us</a></p>
            <p class="foot" style="text-align:center; font-size:20px; font-weight:bold;">
                <a href="guideline.php">Guidelines</a></p>
        </td>
    </tr>
</table>
</body>
</html>