<table width="100%" bgcolor="#ffff00" cellspacing="0">
    <tr>
        <td><form  action="results.php" method="GET"><a href="index.php">
            <Img src = "Andromeda Logo.gif" width="50" height="50">
            <b style="color:purple; font:20px Arial, serif;" id="ndromeda">ndromeda</b></a></td>
        <td><input type="text" id="searchterm" name="searchterm" size="100"
            style="padding: 12px; font-size: 20px; margin-right: auto;"></td>
        <td><input type="submit" value="Search" style=" background-color:purple; 
        font-size:30px; color:white; margin-right: auto;">
        </form></td>
    </tr>
</table>

<table width="100%" bgcolor="#00000" border="0" cellpadding="0" style="text-align: center;">
    <tr>
        <td><p class="head" style="text-align:center; font-size:20px; font-weight:bold; display:inline;">
            <a href="accountlogin.php">Account</a></p></td>
        <td><p class="head" style="text-align:center; font-size:20px; font-weight:bold; display:inline;">
            <a href="orders.php">Orders</a></p></td>
        <td><p class="head" style="text-align:center; font-size:20px; font-weight:bold; display:inline;">
            <a href="lists.php">Lists</a></p></td>
        <td><p class="head" style="text-align:center; font-size:20px; font-weight:bold; display:inline;">
            <a href="subscription.php">Subscriptions</a></p></td>
        <td><p class="head" style="text-align:center; font-size:20px; font-weight:bold; display:inline;">
            <a href="lessor.php">Become a Lessor</a></p></td>
        <td><p class="head" style="text-align:center; font-size:20px; font-weight:bold; display:inline;">
            <a href="specials.php">Specials</a></p></td>
        <td><p class="head" style="text-align:center; font-size:20px; font-weight:bold; display:inline;">
            <a href="adminlogin.php">Administrator Login</a></p></td>
    </tr>
</table>